name: flutter_movies_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.0.2 <4.0.0"

dependencies:
    cached_network_image: ^3.2.3
    dio: ^5.1.2
    flutter:
        sdk: flutter
    freezed_annotation: ^2.2.0
    infinite_scroll_pagination: ^3.2.0
    intl: ^0.18.1
    json_annotation: ^4.8.1
    logger: ^1.3.0
    path: ^1.8.3
    path_provider: ^2.0.15
    provider: ^6.0.5
    sqflite: ^2.2.8+4

dev_dependencies:
    build_runner: ^2.4.4
    flutter_test:
        sdk: flutter
    freezed: ^2.3.4
    json_serializable: ^6.7.0
    lint: ^2.0.1

flutter:
    uses-material-design: true
    assets:
        - assets/config/
